### ISSUE TITLE
Some general comments 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticFormsSelect#1]
After a quick (really) look the following could be improved to ease maintainability:

- [x] DIR structure (src, tests, res, i18n etc.)
- [x] Use a PHP namespace such as `SFS`
- [x] Methods should be non static (if you could make this happen then I might spend 5 min to write one or two rudimentary tests)
- [x] Objects should be injected (Parser, ParserOptions etc.) to improve testability and make the dependency visible
- [x] Having JS script elements here [0] may cause issues with MW when doing an arbitrary `$wgOut->addInlineScript("$script\n");`
- [x] `SemanticFormsSelect::SF_Select` should go into its own class
- [x] `SemanticFormsSelect::QueryExecution`, `SemanticFormsSelect::FunctionExecution` as it is used only by the API
```
global $wgParser, $wgSF_Select_debug;
$semanticFormsSelectAPIHandler = new SemanticFormsSelectAPIHandler( $wgParser)
$semanticFormsSelectAPIHandler->setDebugState( $wgSF_Select_debug )
$semanticFormsSelectAPIHandler->doExecuteQueryFor( ... )

$semanticFormsSelectAPIHandler->doExecuteFunctionFor( ... )
```

- `scriptSelect.js`seems to do several things, its hard to make sense of what it is doing
- JS function styling, [1,2,3]

```
jQuery(function()
{
```
vs
```
( function ( $, mw ) {

	'use strict';

	$( function ( $ ) {

	} );
}( jQuery, mediaWiki ) );
```

[0] https://github.com/SemanticMediaWiki/SemanticFormsSelect/blob/master/SemanticFormsSelect.classes.php#L133-L155
[1] https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript#Structure
[2] http://addyosmani.com/blog/essential-js-namespacing/
[3] https://github.com/SemanticMediaWiki/SemanticCite/blob/master/res/scite.cache.js#L22-L23

**Comment by toniher** [comment]
Thanks a lot! I'll test in a couple of wikis. Considering namespaces are used, we should assume PHP >= 5.4 in composer.json, shouldn't we?

**Comment by mwjames** [comment]
>  we should assume PHP >= 5.4 in composer.json, shouldn't we?

Not sure why, [0] states (PHP 5 >= 5.3.0) and is the same for all the other SMW extensions.

[0] http://php.net/manual/en/language.namespaces.rationale.php

**Comment by toniher** [comment]
ah! perfect. I was wrong all this time :)

**Comment by mwjames** [comment]
@kghbln Not sure this one needs a i18n review but it would be nice (if your time allows it) to have "our i18n expert" to give a thumb up/down on the clean-up effort.

**Comment by mwjames** [comment]
@toniher By the way, the import xml from the help page was a great help because without them I would have not made the clean-up as they gave a good indication what worked and what did not.

**Comment by toniher** [comment]
@mwjames You're right. I think it would make sense to import it into the repo.

**Comment by mwjames** [comment]
Imported the XML to [0] with examples now working with `#subobject`, no SIO required for the [1] example.

[0] http://sandbox.semantic-mediawiki.org/wiki/Semantic_Forms_Select_demo
[1] http://sandbox.semantic-mediawiki.org/wiki/Special:FormEdit/DemoAjax3
