### ISSUE TITLE
Travis ci errors for config sfgFormPrinter 

### ISSUE THREAD

**Issue by paladox** [SemanticMediaWiki/SemanticFormsSelect#14]
Hi in https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/104727726 I am getting these errors

Notice: Undefined index: sfgFormPrinter in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticFormsSelect/SemanticFormsSelect.php on line 87

PHP Fatal error:  Call to a member function setInputTypeHook() on a non-object in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticFormsSelect/SemanticFormsSelect.php on line 87

Fatal error: Call to a member function setInputTypeHook() on a non-object in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticFormsSelect/SemanticFormsSelect.php on line 87

The reason why you never spotted this is because the test stops at you need to use semantic forms 2.8 or higher.

Please fix that config.

**Comment by paladox** [comment]
@mwjames this config needs fixing please.

**Comment by mwjames** [comment]
> @mwjames this config needs fixing please.

This does not need fixing because in the regular Travis set with Composer this issue does not appear and it only appears because of the whole `extension.json` changes which is exactly what I pointed out here https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1367.

**Comment by paladox** [comment]
It happends here https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/104973263

**Comment by paladox** [comment]
I I didn't include extension.json in there. I am trying to fix it just in php not using extension.json. Seems that it gets to saying you need to use 2.8 of semanticforms or higher and then doesent check code pass that so I fix that.

**Comment by mwjames** [comment]
To be clear

> Hi in https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/104727726 I am getting these errors

The reference to for https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/104727726 points to "Pull Request #8 Add extension.json and a posible fix for composer"

> It happends here https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/104973263

The reference to https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/104973263 returns with "b>Error:</b> This version of <a href="https://github.com/SemanticMediaWiki/SemanticFormsSelect/">SemanticFormsSelect</a> is only compatible with Semantic Forms 2.8 or above. You need to upgrade <a href="https://www.mediawiki.org/wiki/Extension:Semantic_Forms">Semantic Forms</a> first."

**Comment by paladox** [comment]
Yes also in different mw versions it shows the error is todo with this config.

**Comment by paladox** [comment]
https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/104977902

**Comment by paladox** [comment]
https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/15

**Comment by mwjames** [comment]
All I can say is that tests with release 1.3.0 (which where reviewed by me) did pass [0] any changes to Travis or Composer beyond that point (and now causing a "Error: This version of SemanticFormsSelect is only compatible with Semantic Forms 2.8 or above. You need to upgrade Semantic Forms first."") where not reviewed by me.

[0] https://travis-ci.org/SemanticMediaWiki/SemanticFormsSelect/jobs/94016778

**Comment by paladox** [comment]
Ok.

It seems to pass for you. When I uploaded a patch for a travis change that updated mediawiki it showed a different error. So I'm not sure why it works for you.

**Comment by mwjames** [comment]
#16 has the base line to pass the tests for SFS with 1.3* + SF 3.4.* + SMW + MW, and Composer therefore any changes that break those tests need to be addressed.

**Comment by paladox** [comment]
Hi I doint believe semanticforms is broken for this extension I believe that we are not autoloading it meaning we are not testing against it.
