### ISSUE TITLE
Input not populated when parent input only has one value

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticFormsSelect#31]
Hello,

I have SF_Select inputs for countries, cities and streets.
If I select a country, the city input is populated with the cities from that country and if I select a city, the street input is populated with streets from this city.
The problem is if the selected country has only one city, the street input is never populated.

This issue has also been reported by someone else here: https://www.mediawiki.org/wiki/Topic:T3ne0kmum6biv3eo

**Comment by JeroenDeDauw** [comment]
Thanks for opening this issue. Labeling it as an enhancement request as this seems to be a missing feature rather than a bug.
