### ISSUE TITLE
Issue when returned value contains ","

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticFormsSelect#32]
When one of the returned values contains `,`, it is incorrectly split.
I would be useful to be able to select a different separator.

**Comment by toniher** [comment]
I would dare to say this is already working. You need to add sep twice, in the query and in the parser function. Below using '*' as separator: 

{{{field|Protocol1|input type=SF_Select|query=((Category:Protocol))((Protocol Belongs to Project::@@@@));format~list;sep~*;link~none;headers~hide;limit~200|sametemplate|field=Project1|sep=*}}}

More at: https://sandbox.semantic-mediawiki.org/wiki/Semantic_Forms_Select_demo

**Comment by kghbln** [comment]
@toniher That's great news! I you @Rudloff could confirm this on your local wiki ... In this case it is a matter of documentation since this is not too intuitive, I guess.

**Comment by Rudloff** [comment]
You're right, this works. Thanks a lot!

**Comment by kghbln** [comment]
Cool, thanks a lot. Added the [respective docu to MediaWiki.org](https://www.mediawiki.org/w/index.php?title=Extension%3ASemantic_Forms_Select&type=revision&diff=2359744&oldid=2318845). Feel free to improve.
