### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticFormsSelect#44]
- [x] Update release notes - https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/48
- [x] Update readme - https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/49
- [x] Update version number (2.0.0) - https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/50
  - [x] SemanticFormsSelect.php
- [x] Finalize release notes (add #51, release date, one unaccounted improvement )
- [x] Create tag
- [x] Announce via mail
- [x] Do a release tweet on Twitter
- [x] Add extension to code documentation generation ([s-mw.o - issue 8](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/8))

**Comment by kghbln** [comment]
What about these pulls: 

1. https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/33
2. https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/34
3. https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/37

**Comment by kghbln** [comment]
- [ ] Finalize release notes
- [ ] Update version number (2.0.0)
  - [ ] SemanticFormsSelect.php
- [ ] Create tag
- [ ] Announce via mail
- [ ] Do a release tweet on Twitter

**Comment by kghbln** [comment]
I must note that PF must be invoced with `wfLoadExtension( 'PageForms' );` even if pulled via Composer else the setup will not work. This is something that must be noted in the README.

**Comment by kghbln** [comment]
There was a [report](https://www.mediawiki.org/w/index.php?title=Topic:T53yxcgh3jz3u5t4&topic_showPostId=tgdw70b479fa9moc#flow-post-tgdw70b479fa9moc) that installing it is now working confirming my https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/44#issuecomment-263418602. Let's see what https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/45 is about.

**Comment by mwjames** [comment]
2.0 contribution notice to include @Seb35, @paladox, and @Rudloff

**Comment by mwjames** [comment]
> I must note that PF must be invoced with wfLoadExtension( 'PageForms' );

Seeking some advice in https://phabricator.wikimedia.org/T152263.

**Comment by kghbln** [comment]
> Seeking some advice in https://phabricator.wikimedia.org/T152263.

Given the response it may take to long to wait. I think we should not wait for this to be possible so for the time being a manual loading is the only way out. This extension has seen to much momentum to wait longer I guess.

**Comment by kghbln** [comment]
> 2.0 contribution notice to include @Seb35, @paladox, and @Rudloff

Definitely!!

**Comment by mwjames** [comment]
> Given the response it may take to long to wait. I think we should not wait for this to be possible so for the 

Sure, it is just as reference that I raised flag on the WMF side.

**Comment by kghbln** [comment]
> 2.0 contribution notice to include @Seb35, @paladox, and @Rudloff

I have just updated the release-notes and the readme so we are getting close to the actual release I believe.

**Comment by Seb35** [comment]
Great, great, great! Thanks for moving forward this step. I’m not sure I can review before Saturday, but Saturday at the latest.

**Comment by kghbln** [comment]
If there are no objections I could do the release on Monday

**Comment by mwjames** [comment]
> If there are no objections I could do the release on Monday

PS: Don't wait for me to merge.

**Comment by kghbln** [comment]
> PS: Don't wait for me to merge.

Ok, there is nothing which I could possibly break by adding the date to the Release-Notes, at least I hope. :)

**Comment by Seb35** [comment]
Ok, re-tested with MW 1.29, 1.28, 1.27 + SMW 2.4.3 + PF 4.0.2 + SFS 2.0.0.

I opened #52 to warn users in case it does not work.

I have issues with MW 1.28 (the standard request (without JS involved) only shows two empty items instead of one empty and one real); I will try to find why but could you test yourself this specific case? (perhaps I have some wrong thing somewhere)

**Comment by kghbln** [comment]
@Seb35 Thanks for the clarification in the README and testing!!

> I have issues with MW 1.28 (the standard request (without JS involved) only shows two empty items instead of one empty and one real)

I am not sure if I understand correctly so could try to test this on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Main_Page) which runs MW 1.28. I will now postpone the release.

If there is an issue MW 1.29 this will not be a blocker since it is not officially released yet.

**Comment by mwjames** [comment]
> I have issues with MW 1.28 (the standard request (without JS involved) only shows two empty items instead of one empty and one real); I will try to find why but could you test yourself this specific case? (perhaps I have some wrong thing somewhere)

I think you guys should make a release otherwise this is going in circles, if a solution is found then making another release/tag shouldn't be that hard.

I quickly went through [0] to see whether the examples work or not (as in changing a value to change a dependency etc.) and it doesn't seem worse of then before.

@Seb35 If you have an example then [1] is the category to go.

[0] https://sandbox.semantic-mediawiki.org/wiki/Semantic_Forms_Select_demo
[1] https://sandbox.semantic-mediawiki.org/wiki/Cat%C3%A9gorie:Semantic_Forms_Select_example

**Comment by kghbln** [comment]
> I think you guys should make a release otherwise this is going in circles, if a solution is found then making another release/tag shouldn't be that hard.

:+1: Ok, will do the release on Monday.

**Comment by kghbln** [comment]
All has happened now. I guess having this out is a big progress in comparison to not doing it. Thanks to all of you!
