### ISSUE TITLE
JS error with latest master

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticFormsSelect#45]
With Page Forms 4.0.2 and SFS 483f370, nothing happens when I select something in a select input.

I have a series of select inputs like this:
![image](https://cloud.githubusercontent.com/assets/840125/20689455/c90e1d3e-b5c5-11e6-8207-143872738160.png)
The second one is populated based on what has been selected in the first one, and so on...
It works correctly with SFS 1.3 and SF 3.3.2 but with the latest master nothing happens.

I get nothing in the browser console when I select something (no AJAX query and no JS error) but I get this JS error during page load:
```
23:59:08,454 Error: Syntax error, unrecognized expression: input[name=Recherche avancée\[pays\]] 1 load.php:1496:8
	Sizzle</Sizzle.error http://localhost/archi-mediawiki/load.php:1496:8
	Sizzle</Sizzle.tokenize http://localhost/archi-mediawiki/load.php:2113:4
	Sizzle</Sizzle.select http://localhost/archi-mediawiki/load.php:2517:20
	Sizzle http://localhost/archi-mediawiki/load.php:893:9
	.find http://localhost/archi-mediawiki/load.php:2733:4
	jQuery.fn.init http://localhost/archi-mediawiki/load.php:2850:14
	jQuery http://localhost/archi-mediawiki/load.php:73:10
	<anonyme> http://localhost/archi-mediawiki/extensions/SemanticFormsSelect/res/scriptSelect.js:308:7
	<anonyme> http://localhost/archi-mediawiki/extensions/SemanticFormsSelect/res/scriptSelect.js:183:3
```
(However, I get a similar error with the old version and the form works so I'm not sure it is relevant.)

**Comment by Rudloff** [comment]
I think I managed to reproduce it on sandbox: https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:RunQuery/SFS_test

**Comment by kghbln** [comment]
@Rudloff Thanks for reporting and setting up an example on sandbox. I have now also asked @Seb35 to give it a try who also just installed it on a wiki.

**Comment by Seb35** [comment]
With Firefox, I was able to reproduce it on MW 1.29alpha (no AJAX and no JS error, not even the one given above) and I see the error on the sandbox. However I don’t have any idea how to solve it.

If one consider jQuery Sizzle (which emits the top error) don’t have a bug (working hypothesis), the error is located on https://github.com/SemanticMediaWiki/SemanticFormsSelect/blob/master/res/scriptSelect.js#L308. Given this file was not changed since 21 September 2015, perhaps some JS resource was forgotten during the recent change in extension loading (just an idea of something which can be checked).

**Comment by Seb35** [comment]
Searched a bit, here are my first results, I can not continue as of now.

1. When trying in Firefox console `$('select[name=SFS test\\[pays\\]]')`, the answer is `Error: Syntax error, unrecognized expression: select[name=SFS test\[pays\]]`.
2. When trying in Firefox console `$('select[name=\'SFS test[pays]\']')`, the answer is `Object { length: 1, prevObject: Object, context: HTMLDocument → SFS_test, selector: "select[name='SFS test[pays]']", 1 de plus… }` (better).

I tried to add this in `res/scriptSelect.js`, but unsuccessful for now (perhaps a mistake on my side).

**Comment by Seb35** [comment]
I investigated further and I have difficulties understanding what is happening. My previous comment was probably out-of-scope regarding this bug. My results:

* the only JS in SFS didn’t changed since SFS 1.3 so it cannot be that,
* the HTML didn’t changed between SFS 1.3 so it cannot be some HTML new structure

The only remaining possibility (I guess) is the JS in PageForms changed in a way it becames incompatible with SFS.

**Comment by Seb35** [comment]
End of the story: with the change SemanticForms → PageForms, there is in SFS script res/scriptSelect.js: `$( "form#sfForm" )`. Change it to `$( "form#pfForm" )`. And it works.

**Comment by kghbln** [comment]
@Seb35 Thanks a lot for digging into this and finding the solution. I guess you deserve to do the respective pull request. :) Great work!

**Comment by kghbln** [comment]
I would have loved to update sandbox to latest master, but somehow composer fails to do so. It just clones 483f3702a7daa9f3b98a6f9b7daa2288b6c8978e and that's it. :|

**Comment by Seb35** [comment]
I had also this commit when downloading with Composer. I guess there is no push hook on GitHub, see https://packagist.org/about#how-to-update-packages. Without it, it is only updated once a week (see the same page).

**Comment by kghbln** [comment]
Usually master is pulled immediately and the last update happened a fortnight ago so I created https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/47 to track this.

**Comment by kghbln** [comment]
So sandbox is updated now.

**Comment by Rudloff** [comment]
The form inputs on the usecase on sandbox are now rendered as text inputs. I guess it means SFS is not properly loaded.

**Comment by kghbln** [comment]
> I guess it means SFS is not properly loaded.

Indeed SFS was no longer automatically loaded via composer after I upgraded to latest master, which I assumed would be the case. Now showing up on Special:Version and the example is working too.

**Comment by Rudloff** [comment]
I confirm the issue is fixed on sandbox and on my server.
