### ISSUE TITLE
Interaction with packagist.org broken

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticFormsSelect#47]
Probably the webhook providing the syncing between GitHub and Packagist is broken for some reason (https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/45#issuecomment-264306462). Master is no longer immediately pulled since https://github.com/SemanticMediaWiki/SemanticFormsSelect/commit/483f3702a7daa9f3b98a6f9b7daa2288b6c8978e I tried to send a test payload but nothing happens except for the note that it is was done with no concluding message etc. Probably another indicator that it is not working. Since you @mwjames set up packagist for this extension I'd rather not fiddle here ...

**Comment by mwjames** [comment]
> Since you @mwjames set up packagist for this extension I'd rather not fiddle here ...

No, I don't have access to the packagist side [0] but @JeroenDeDauw @toniher do. I'm not sure why the connection doesn't work, at least assigning other people to the repo would allow to manually purge the package.

[0] https://packagist.org/packages/mediawiki/semantic-forms-select

**Comment by kghbln** [comment]
> I'm not sure why the connection doesn't work,

Great to read since it's not me being to stupid to work on this. :)

> I'm not sure why the connection doesn't work, at least assigning other people to the repo would allow to manually purge the package.

That's probably a good idea. I control two packages with my personal account and both you and Jeroen as well as SMW are in control, too.

**Comment by kghbln** [comment]
Same for the 3.4.2 farewell release of Semantic Maps. Perhaps @JeroenDeDauw accidentally disabled the whole lot ;)

**Comment by JeroenDeDauw** [comment]
If it is not updating, that suggests the GitHub hook settings are wrong. You do need access to Packagist to get the auth token though. Fixed for SM now. And for this extension I see the SMW Packagist account has access, so I suppose someone else already acted here. (James, you do have access to this account right?)

**Comment by mwjames** [comment]
>  (James, you do have access to this account right?)

No.

**Comment by JeroenDeDauw** [comment]
Well, send me a public key I can use to encrypt the credentials with and I'll send them to you

**Comment by JeroenDeDauw** [comment]
Nvm, I'm adding Packagist user `mwjames` to the relevant packages. I saw the name in the config of this GH repo, so am taking that as enough proof it is your account.

**Comment by JeroenDeDauw** [comment]
Nvm, I'm adding Packagist user `mwjames` to the relevant packages. I saw the name in the config of this GH repo, so am taking that as enough proof it is your account.

**Comment by kghbln** [comment]
> (James, you do have access to this account right?)

This info can easily be accessed via [this page](https://www.semantic-mediawiki.org/wiki/semantic-mediawiki.org:Services_accounts). In case James has access not it should be updated.

Apart from that: The sync works again. Just pulled latest master without worries. Thanks a lot for fluff!
