### ISSUE TITLE
Support "mapping property" / "mapping template" in value field

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticFormsSelect#53]
```
 {{{field|P2Protocols3|input type=SF_Select|query=((Category:Protocol))((Protocol Belongs to Project::@@@@));?Has Name;format~list;sep~,;link~none;headers~hide;limit~
200|sametemplate|field=Project1|label}}}
```

...will fail, if field _Project1_ uses _mapping property_ or _mapping template_ (e.g. to support Display Title).

Any ideas / suggestions?

**Comment by kghbln** [comment]
This might perhaps be even a problem with Page Forms itself since I did not manage to get the mapping template working for it without using SFS. However the examples are utterly poor and nobody cares to fluff so I might be doing something wrong.

**Comment by gesinn-it** [comment]
@kghbln do we have a sandbox on _smw.org_ where SFS can be tested? I don't see SFS installed:

https://www.semantic-mediawiki.org/wiki/Special:Version

**Comment by kghbln** [comment]
> do we have a sandbox on smw.org where SFS can be tested?

Yes, [over there](https://sandbox.semantic-mediawiki.org/wiki/Main_Page)

**Comment by kghbln** [comment]
@gesinn-it I am not sure if you saw my post.

**Comment by jaideraf** [comment]
Just to endorse it, I also need a _mapping property_ to show the values of _Display title of_ in a SFS field.

**Comment by DengroWikibase** [comment]
And just to endorse what Jaideraf endorsed: me too!

**Comment by gesinn-it** [comment]
I did not have the time to verify in the sandbox...

**Comment by gesinn-it** [comment]
... okay, I now completely fixed this issue. My Pull Request has been updated. To fully support mapping, Page Forms needs to support this (_"value-initial"_). The relevant patch [1] is waiting for review. Feel free to add comments / vote for this on Gerrit.

[1] https://gerrit.wikimedia.org/r/#/c/348702/

In my test environment, the following test passed successfully:

_Tokens without 'value-initial':_
[ok] without mapping, new page
[ok] without mapping, edit page
[n/a] with mapping, new page
[n/a] with mapping, edit page

_Combobox without 'value-initial':_
[ok] without mapping, new page
[ok] without mapping, edit page
[n/a] with mapping, new page
[n/a] with mapping, edit page

_Tokens with 'value-initial':_
[ok] without mapping, new page
[ok] without mapping, edit page
[ok] with mapping, new page
[ok] with mapping, edit page

_Combobox with 'value-initial':_
[ok] without mapping, new page
[ok] without mapping, edit page
[ok] with mapping, new page
[ok] with mapping, edit page
