### ISSUE TITLE
Get I18n rolling

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticFormsSelect#6]
This extension currently does not support I18n. I believe this is a nice to have feature.
- [x] Add I18n // done with https://github.com/SemanticMediaWiki/SemanticFormsSelect/commit/0c7c3e46b5e7e84ea1122423a3fe99102fe17a99
- [x]  Fluff message documentation // done with https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/37
- [x] Ping tw.n

**Comment by kghbln** [comment]
I18n added with https://github.com/SemanticMediaWiki/SemanticFormsSelect/commit/0c7c3e46b5e7e84ea1122423a3fe99102fe17a99

**Comment by kghbln** [comment]
@mwjames Any objections to pinging twn?

**Comment by mwjames** [comment]
> @mwjames Any objections to pinging twn?

:+1:

**Comment by kghbln** [comment]
@Nikerabbit It will be great if this extension could be added to tw.n

**Comment by Nikerabbit** [comment]
Done.

**Comment by kghbln** [comment]
> Done.

Great and thank you. Also just checked if you and Siebrand have push right. So everything should move on smoothly.

**Comment by Seb35** [comment]
I just translated sfs-desc/fr on translatewiki, we will see if it works.
