### ISSUE TITLE
make SFS compliant with recent PF versions

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticFormsSelect#62]
The way SFS implements the custom input type requires updates to be compliant with recent versions of PF. At least the following things needs to be done:

- `class SemanticFormsSelect` should extend `PFFormInput`
- update constructor like:
`public function __construct( $inputNumber, $curValue, $inputName, $disabled, $otherArgs )`
- provide `public static function getName()`
- provide `public function getHtmlText()`
- provide `public static function getParameters()`

**Comment by mwjames** [comment]
>  be compliant with recent versions of PF. 

Means exactly what?

> class SemanticFormsSelect should extend PFFormInput

If possible don't mix responsibilities and add a new class that can be injected somehow, I'd like to avoid a kitchen sink programming style.

**Comment by gesinn-it** [comment]
`class SemanticFormsSelect extends PFFormInput` is the recommended way to create (custom) input types for PF. All PF input types are implemented this way. Also HierarchyBuilder is implemented this way [1]. @yaronkoren please correct me if I'm wrong.

[1] https://github.com/wikimedia/mediawiki-extensions-HierarchyBuilder/blob/master/includes/HierarchyFormInput.php#L25

**Comment by yaronkoren** [comment]
Yes, that's right.

**Comment by mwjames** [comment]
> class SemanticFormsSelect extends PFFormInput is the recommended way to create (custom) input types for PF. All PF input types are implemented

I'd suggest something along:

* Create a new class `FooFormInput` with the required methods inherited from `PFFormInput`
* Move `SemanticFormsSelect` to something like `ParameterProcessor` to handle the query parameter processing isolated from any `PFFormInput` related responsibilities
* Inject `ParameterProcessor` into `FooFormInput` to isolate parameter processing from HTML formatting etc.

Reason is that `ParameterProcessor` can be tested isolated from the `PFFormInput` interface and minimizes the dependence on PF when writing unit tests.

Travis runs on this repo and writing unit tests isn't that difficult (I give a hand on the test part if you require it).

**Comment by gesinn-it** [comment]
cool, sounds like a plan. I'll try implement it as suggested. Thx for your feedback @mwjames .

**Comment by gesinn-it** [comment]
status update: made some good progress this week refactoring SFS. Need to separate a few things as suggested by @mwjames. I hope to come up with a PR for this next week. This will include a fix for #59, too.

**Comment by kghbln** [comment]
I believe this is now resolved with the 3.0.0 release of this extension which is afaik at least working with Page Forms 4.3.1
