### ISSUE TITLE
Feature request: separate option label & value

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticFormsSelect#66]
### Setup

- MW version: 1.28.1
- DB (MySQL etc.): MySQL 5.5.55
- PHP version: 5.6.30-0+deb8u1
- SMW version: 2.5.2
- SFS version: 2.1.0
- PF version: 4.1

### Issue

Currently the value of a SFS select option is what is displayed to the user:
```html
<option>foo</option>
```

But it would be nice to have a way to use a different semantic property as label:
```html
<option value="foo">bar</option>
```

(Typically we would need this because some of our pages have a `Full name` property that is different from the actual name of the article.)

**Comment by toniher** [comment]
This was already in the extension before, 'label' parameter (commented here: https://www.mediawiki.org/wiki/Extension:Semantic_Forms_Select). Just in case, added test here: https://sandbox.semantic-mediawiki.org/wiki/Semantic_Forms_Select_demo and it should be in upcoming 3.0.0 release #69

**Comment by kghbln** [comment]
Judging from @toniher's comment I believe that this is part of SFS which was just released.
