### ISSUE TITLE
Make 3.0.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticFormsSelect#69]
Release date: 2018-10-04

- [x] Finalize release notes
- [x] Update "README"
- [x] Update "composer.json" (remove SMW 3.0 dev)
- [x] Update "SemanticFormsSelect.php" (version 3.0.0)
- [x] Update "extension.json" (version 3.0.0)
- [x] Create tag
- [x] Add release to [Wikidata](https://www.wikidata.org/wiki/Q21678495)
- [x] Update [hompage](https://www.mediawiki.org/wiki/Extension:Semantic_Forms_Select)
- [x] Start development of new version 
  - [x] Update "composer.json" (update dev alias)
  - [x] Update "RELEASE NOTES" (start new section)
  - [x] Update "extension.json" (new alpha version)
- [x] Announce via mail
- [x] Do a release tweet on Twitter

**Comment by kghbln** [comment]
@gesinn-it It will be cool if you could give it a shot at providing the updates of your fork for this release. No worries. Take your time. Also I think some changes to Page Forms are in the pipeline for this so ...

**Comment by gesinn-it** [comment]
@kghbln a lot of code has changed and the way of registration with PF has changed (the reason for the current non-functioning of SFS). How about 3.0.0?

**Comment by kghbln** [comment]
> How about 3.0.0?

No objections.

**Comment by kghbln** [comment]
Postponed till https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/64 is resolved.

**Comment by gesinn-it** [comment]
Should be 3.x if it's based on gesinn.it fork (see comments above)

**Comment by kghbln** [comment]
> Should be 3.x if it's based on gesinn.it fork (see comments above)

I guess we already agreed on this.

**Comment by gesinn-it** [comment]
ah okay, how about renaming "Make 2.2.0 release" -> "Make 3.x release" to avoid confusion? :-)

**Comment by kghbln** [comment]
Well I was waiting for some activity here. ;) As long as there is no pull we are basically still on 2.2.0 whatever this may be. However, since we probably gain momentum right now ...

**Comment by toniher** [comment]
Hi, I applied different changes to this version (from @gesinn-it version), and it seems to work in my environment (MW 1.27.x, Page Forms, etc.) Here it is: https://github.com/biocorecrg/SemanticFormsSelect -> If OK with you I can try to merge with this so we can do further testing and eventually more users can benefit...

**Comment by mwjames** [comment]
> is: https://github.com/biocorecrg/SemanticFormsSelect -> If OK with you I
> can try to merge with this so we can do further testing and eventually more
> users can benefit...

I'd say go ahead, I have some problems with the `extension.json` that
hosts all sorts of stuff that doesn't belong their (autoclasssing
etc.) but that is an issue that can be resolved later on.

Cheers

**Comment by toniher** [comment]
Well, with last changes: #71, #72, #73, this should be ready for release. Regarding list/plainlist change with SMW 3.0, I might rather comment it here: https://www.mediawiki.org/wiki/Extension:Semantic_Forms_Select Let me know your opinion!

**Comment by kghbln** [comment]
@toniher Please also voice your opinion here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3472. Depending on the outcome the info has to be added to the wiki and RELEASE-NOTES or no action is needed at all. :)

**Comment by toniher** [comment]
So, @kghbln from your experience in releasing, what else do you think it is missing? I can take care of creating the tag if everything is done.

**Comment by kghbln** [comment]
@toniher A precondition to the release was to have plainlist as default which now happend. If you are happy with the docu I will do the release on Thursday.

**Comment by toniher** [comment]
Thanks a lot @kghbln !
