### ISSUE TITLE
Upgrade compatibility with JS library select2

### ISSUE THREAD

**Issue by Seb35** [SemanticMediaWiki/SemanticFormsSelect#82]
### Setup

- MW version: 1.33.0 - 1.35.0
- DB (MySQL etc.): MariaDB 10.1 - 10.2 (not relevant here)
- PHP version: 7.2.24 - 7.3.23 (probably not relevant here)
- SMW version: 3.1.3
- SFS version: 3.0.0
- PF version: 5.1
- Browsers and versions (if applicable): all - confirmed at least with Firefox 84 and Chromium 88

### Issue

With [the update of the JS library select2](https://phabricator.wikimedia.org/T184251) in April 2020, the forms using SFS are not displayed and there is a message `The select2('data') method was called on an element that is not using Select2.` in the debug console.

According to my preliminary researches, it should now be checked beforehand if select2 is initialised on a particular node, see [this](https://web.archive.org/web/20201103120910/https://select2.org/programmatic-control/methods) and [this](https://stackoverflow.com/questions/29854022/is-there-any-way-to-check-if-an-element-has-jquery-select2-already-applied-to-it/29854133#29854133).

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
* Open https://sandbox.semantic-mediawiki.org/wiki/Special:FormEdit/DemoStatic
* Open the console (Ctrl+Shift+K on Firefox, Ctrl+Shift+I on Chrome/Chromium then tab 'Console') and be sure the level 'Error' is activated
* Change one value in the form
* There the red error message `The select2('data') method was called on an element that is not using Select2.`
* PS: on more complicated forms with parametrised fields like [DemoAjax1](https://sandbox.semantic-mediawiki.org/wiki/Special:FormEdit/DemoAjax1), I guess it is the reason the parametrised field is not displayed

**Comment by kghbln** [comment]
Thanks for reporting and potentially have a look into this. To cut it short this extension is only compatible up to Page Forms 4.8

**Comment by Seb35** [comment]
Added reproducing steps on sandbox.smw.org
