### ISSUE TITLE
Error with latest version of Page Forms

### ISSUE THREAD

**Issue by Goldshop** [SemanticMediaWiki/SemanticFormsSelect#87]
### Setup

- MW version: 1.35.2
- DB (MySQL etc.): 10.5.10
- PHP version: 7.4.20
- SMW version: 3.2.3
- SFS version: Latest 3.0 (66f2cf2030bbdf6e6aaf28347d0ee16caff5f2a4)
- PF version: Latest 5.2.1 (d421edf5edd6a439074e8c619927e53d5c1d3710)
- Browsers and versions (if applicable):

### Issue
PHP Fatal error:  Declaration of SFS\SemanticFormsSelectInput::getName() must be compatible with PFFormInput::getName(): string in /var/www/html/extensions/SemanticFormsSelect/src/SemanticFormsSelectInput.php on line 37

Fatal error: Declaration of SFS\SemanticFormsSelectInput::getName() must be compatible with PFFormInput::getName(): string in /var/www/html/extensions/SemanticFormsSelect/src/SemanticFormsSelectInput.php on line 37

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

To reproduce use the latest version of Page Forms.

**Comment by kghbln** [comment]
Thanks for reporting. I am afraid nobody will work on this in the foreseeable future. Anyhow let's hope for the best.

**Comment by gesinn-it-wam** [comment]
This has been fixed in PF 5.3: https://github.com/wikimedia/mediawiki-extensions-PageForms/commit/fe797c67427523e0e764025aa66e40e145341a21
